"""
Generated root files: `.gitignore` (every platform) and `CLAUDE.md` (Claude Code).

Both are emitted by the exporters the same way `README.md` is — they are **not** entries
in `plan.source_tree`. That is deliberate:

- Their content is derived, not scaffolded. `.gitignore` depends on the detected tech
  stack and `CLAUDE.md` on the agents/skills in the plan, so a stored copy would go
  stale the moment the plan changed.
- Every **existing** project picks them up on its next preview / refresh / export with
  no plan migration, because rendering is what produces them.

Stack detection reads the scaffold paths rather than the brief, since the exporter holds
the plan and paths are what the ignore rules actually have to cover.
"""

from __future__ import annotations

from app.models.schemas import ProjectPlan, RuleSpec
from app.services.deduction.solution_design import SDD_FILENAME
from app.services.deduction.work_breakdown import WORK_BREAKDOWN_FILENAME

# Root files this module owns. Listed here so `_is_ide_or_readme` and its mirrors in the
# Angular wizard and the CLI stay in step: these are exporter-generated, never scaffold,
# so they count toward "workspace files" and never toward "source files".
GITIGNORE_FILENAME = ".gitignore"
CLAUDE_MEMORY_FILENAME = "CLAUDE.md"


def detect_stack_tags(plan: ProjectPlan) -> set[str]:
    """
    Infer which ignore blocks this project needs from its scaffold paths.

    Path-based rather than brief-based so it works identically for a plan generated
    today and one generated months ago.
    """
    paths = [
        (spec.path or "").replace("\\", "/").lstrip("/").lower()
        for spec in (plan.source_tree or [])
    ]
    blob = "\n".join(paths)
    tags: set[str] = set()

    if any(p.endswith(".py") for p in paths) or "requirements.txt" in paths:
        tags.add("python")
    if any(p.endswith((".ts", ".tsx", ".js", ".jsx")) for p in paths) or any(
        p.endswith("package.json") for p in paths
    ):
        tags.add("node")
    # Angular first: it also has `.ts` under a `frontend/`, so checking Next first would
    # mislabel it and emit `.next/` instead of `.angular/`.
    if "angular" in blob or ".component.ts" in blob:
        tags.add("angular")
    elif "next" in blob or any(
        p.startswith("frontend/app/") and p.endswith(".tsx") for p in paths
    ):
        # `frontend/app/*.tsx` is the Next App Router shape the scaffold builds — matching
        # only `layout.tsx` missed trees whose first route file is `page.tsx`.
        tags.add("next")
    if any(p.startswith("frontend/templates/") for p in paths):
        tags.add("jinja")
    if "sqlite" in blob or any(p.endswith((".db", ".sqlite3")) for p in paths):
        tags.add("sqlite")
    if "dockerfile" in blob or "docker-compose" in blob:
        tags.add("docker")
    if "alembic" in blob or "migrations" in blob:
        tags.add("migrations")

    # Nothing recognisable (a plan with an empty tree) still deserves the shared blocks.
    return tags


def _block(title: str, entries: list[str]) -> list[str]:
    return [f"# {title}", *entries, ""]


def render_gitignore(plan: ProjectPlan) -> str:
    """
    Tech-stack-appropriate `.gitignore` with real rules — not a `Role:` placeholder.

    Only blocks the detected stack needs are emitted, so a Python-only API does not ship
    `node_modules/` noise. The AI artifacts (`.claude/`, `.cursor/`, `.windsurf/`, and GitHub Copilot-specific
    `.github/` customization files) are deliberately **not** ignored: they are the point
    of the export and belong in git.
    """
    tags = detect_stack_tags(plan)
    lines: list[str] = [
        f"# .gitignore for {plan.project_name}",
        "# Generated by AgentCraft from this project's tech stack.",
        "",
    ]

    lines += _block(
        "Secrets and local config",
        [
            ".env",
            ".env.*",
            "!.env.example",
            "*.pem",
            "*.key",
            "secrets.json",
        ],
    )

    if "python" in tags:
        lines += _block(
            "Python",
            [
                "__pycache__/",
                "*.py[cod]",
                "*$py.class",
                ".venv/",
                "venv/",
                "env/",
                "*.egg-info/",
                "build/",
                "dist/",
                ".pytest_cache/",
                ".mypy_cache/",
                ".ruff_cache/",
                ".coverage",
                "coverage.xml",
                "htmlcov/",
            ],
        )

    if "node" in tags or "next" in tags or "angular" in tags:
        node_entries = [
            "node_modules/",
            "npm-debug.log*",
            "yarn-error.log*",
            "pnpm-debug.log*",
            ".pnpm-store/",
            "*.tsbuildinfo",
            "coverage/",
        ]
        if "next" in tags:
            node_entries += [".next/", "out/"]
        if "angular" in tags:
            node_entries += [".angular/", "dist/"]
        if "next" not in tags and "angular" not in tags:
            node_entries += ["dist/", "build/"]
        lines += _block("Node / TypeScript", node_entries)

    if "sqlite" in tags:
        lines += _block("SQLite", ["*.db", "*.db-journal", "*.sqlite", "*.sqlite3"])

    if "migrations" in tags:
        lines += _block(
            "Migrations (keep versioned scripts; ignore local scratch)",
            ["*.sql.bak", "alembic/versions/*.pyc"],
        )

    if "docker" in tags:
        lines += _block("Docker", ["docker-compose.override.yml", ".docker/"])

    lines += _block(
        "Editors and OS",
        [
            ".vscode/*",
            "!.vscode/extensions.json",
            ".idea/",
            "*.swp",
            ".DS_Store",
            "Thumbs.db",
        ],
    )

    lines += _block(
        "Logs and scratch",
        ["logs/", "*.log", "tmp/", ".cache/"],
    )

    lines += [
        "# AI workspace — intentionally tracked.",
        "# .claude/ .cursor/ .windsurf/ .github/copilot-instructions.md "
        "# .github/instructions/ .github/agents/ .github/skills/ AGENTS.md CLAUDE.md "
        f"{WORK_BREAKDOWN_FILENAME} and {SDD_FILENAME} are part of this",
        "# project's source of truth. Commit them so the whole team gets the same agents,",
        "# skills and rules. Only machine-local IDE state is ignored:",
        ".claude/settings.local.json",
        ".cursor/settings.local.json",
        "",
    ]
    return "\n".join(lines)


def _layout_lines(plan: ProjectPlan) -> list[str]:
    """
    Only describe directories this plan actually has.

    A layout bullet for a `frontend/` that was never scaffolded sends Claude looking for
    files that do not exist — worse than saying nothing.
    """
    paths = {
        (spec.path or "").replace("\\", "/").lstrip("/") for spec in (plan.source_tree or [])
    }
    has = lambda prefix: any(p.startswith(prefix) for p in paths)  # noqa: E731

    out: list[str] = []
    if "main.py" in paths:
        out.append("- `main.py` — process entrypoint. Boots config and starts the server; no logic here.")
    if has("backend/api/"):
        out.append("- `backend/api/` — routes and FastAPI dependencies. Validate, delegate, return.")
    if has("backend/services/"):
        out.append("- `backend/services/` — business rules. Everything domain-specific lives here.")
    if has("backend/repositories/"):
        out.append("- `backend/repositories/` — the only layer that touches the database.")
    if has("backend/models/") or has("backend/schemas/"):
        out.append("- `backend/models/` + `backend/schemas/` — ORM entities and API DTOs. Keep them separate.")
    if has("backend/core/"):
        out.append("- `backend/core/` — settings, security, DB session factory.")
    if has("backend/tests/"):
        out.append("- `backend/tests/` — pytest. Add tests beside the layer you changed.")
    if has("frontend/templates/"):
        out.append("- `frontend/templates/` + `frontend/static/` — Jinja pages and browser assets.")
    elif has("frontend/"):
        out.append("- `frontend/` — UI. `app/` routes, `features/` domain slices, `services/` API clients.")
    out.append(
        "- `.claude/agents/` + `.claude/skills/` + `.claude/rules/` — this project's agents, "
        "skills and rules."
    )
    return out


def _command_lines(plan: ProjectPlan) -> list[str]:
    tags = detect_stack_tags(plan)
    cmds: list[str] = []
    if "python" in tags:
        cmds += [
            "pip install -r requirements.txt",
            "cp .env.example .env          # then fill in real values",
            "uvicorn main:app --reload     # API on :8000",
            "pytest -q                     # tests",
        ]
    if "angular" in tags:
        cmds += ["cd frontend && npm install && ng serve"]
    elif "next" in tags or "node" in tags:
        cmds += ["cd frontend && npm install && npm run dev"]
    return cmds or ["# No build tooling detected yet — see README.md."]


def render_claude_md(plan: ProjectPlan, *, rules: list[RuleSpec] | None = None) -> str:
    """
    Short project memory for Claude Code.

    Claude Code loads `CLAUDE.md` from the project root into context at the **start of
    every session**, so its cost is paid on every single prompt. That is why this file is
    deliberately brief and points at `README.md` / `WORKBREAKDOWN.md` instead of
    repeating them: a long memory file crowds out the actual task and gets skimmed. What
    earns its place here is only what Claude cannot infer from the code — where the
    layers are, which boundaries not to cross, and how to run things.

    Layer conventions are no longer restated here: they live in `.claude/rules/` and are
    pulled in by the `@` imports below, so there is exactly one copy to keep correct.
    `rules` comes from the exporter because Claude rules are derived from the plan rather
    than stored on it.
    """
    from app.services.deduction.project_rules import claude_rule_import_lines

    rule_list = list(rules or [])
    always_imports, scoped_refs = claude_rule_import_lines(rule_list)
    agent_names = [a.name for a in plan.agents]
    skill_names = [s.name for s in plan.skills]

    lines: list[str] = [
        f"# {plan.project_name}",
        "",
        " ".join((plan.summary or "Generated workspace.").split())[:400],
        "",
        "## Start here",
        f"1. Read **Phase overview** in `{WORK_BREAKDOWN_FILENAME}`.",
        f"2. Work one phase at a time — ask: `Implement Phase 1 from {WORK_BREAKDOWN_FILENAME}`.",
        "3. Finish every item under **Test & acceptance** before starting the next phase.",
        "",
        # Pointed at rather than imported: the design document is long, and paying for it on
        # every prompt would crowd out the task. Open it when a decision needs its reasoning.
        f"Why the solution is shaped this way — requirements, architectural views, risks, "
        f"acceptance criteria: `{SDD_FILENAME}`.",
        "Full reference (all file purposes, agents, skills, rules): `README.md`.",
        "",
        "## Layout",
        *_layout_lines(plan),
        "",
    ]

    if always_imports:
        lines += [
            "## Rules — always apply",
            "",
            # `@path` is how Claude Code pulls another file into context. Importing only the
            # always-on rules is what keeps this file cheap; the scoped ones are listed
            # below for Claude to open when it is actually in those paths.
            *always_imports,
            "",
        ]
    if scoped_refs:
        lines += [
            "## Rules — read when relevant",
            "",
            *scoped_refs,
            "",
        ]
    if not rule_list:
        lines += [
            "## Conventions",
            "- Keep routes thin: validate with schemas, call a service, return a DTO.",
            "- Only repositories run queries. Services never touch a DB session directly.",
            "- Read config through `backend/core/config.py`; never hardcode a secret.",
            "- Scaffold files ship as a `Role:` docstring — replace one when its phase calls for it.",
            "- Add or update tests in the same change as the code.",
            "",
        ]

    lines += [
        "## Commands",
        "```bash",
        *_command_lines(plan),
        "```",
        "",
        "## Agents and skills",
    ]

    if agent_names:
        shown = ", ".join(f"`{n}`" for n in agent_names[:8])
        more = f" (+{len(agent_names) - 8} more)" if len(agent_names) > 8 else ""
        lines.append(f"{len(agent_names)} agents in `.claude/agents/`: {shown}{more}.")
    else:
        lines.append("No agents generated for this project.")
    if skill_names:
        shown = ", ".join(f"`{n}`" for n in skill_names[:8])
        more = f" (+{len(skill_names) - 8} more)" if len(skill_names) > 8 else ""
        lines.append(f"{len(skill_names)} skills in `.claude/skills/`: {shown}{more}.")
    lines.append(
        "Claude Code discovers both automatically — delegate a task to an agent by name "
        "rather than doing specialist work inline."
    )
    lines.append("")
    return "\n".join(lines)

