export type ProjectState =
  | 'CREATED'
  | 'AWAITING_DOCS'
  | 'AWAITING_INTERVIEW'
  | 'CONTEXT_READY'
  | 'PLATFORM_SELECTED'
  | 'GENERATING'
  | 'READY_FOR_REVIEW'
  | 'EXPORTED';

export interface InterviewQuestion {
  id: string;
  prompt: string;
  required: boolean;
  answer?: string | null;
}

export interface SourceFileSpec {
  path: string;
  purpose: string;
  content?: string;
}

export interface ProjectPlan {
  project_name: string;
  summary: string;
  agents: any[];
  skills: any[];
  rules: any[];
  mcp_servers: any[];
  source_tree?: SourceFileSpec[];
  /** Persisted Export-tab file edits (path → body). Applied on preview/zip. */
  file_overrides?: Record<string, string>;
  /** Detailed phased WORKBREAKDOWN.md body (editable; exported beside README). */
  work_breakdown?: string;
  /** True when generated by Bedrock (not the instant fallback stub). */
  work_breakdown_llm?: boolean;
  /** True when every phase is fully written (not truncated). */
  work_breakdown_complete?: boolean;
  /** Solution Design Document SDD.md body (editable; exported beside README). */
  solution_design?: string;
  /** True when generated by Bedrock (not the deterministic fallback). */
  solution_design_llm?: boolean;
  /** True when every numbered section is present and in order. */
  solution_design_complete?: boolean;
}

export interface UploadedDocument {
  filename: string;
  size_bytes: number;
  content_type: string;
  chars_extracted: number;
  uploaded_at?: string | null;
}

export interface ProjectBrief {
  problem_statement: string;
  document_text: string;
  /** Uploaded source documents. Empty for projects created before this shipped. */
  documents?: UploadedDocument[];
  interview_answers: Record<string, string>;
  tech_stack: string;
  domains: string[];
  constraints: string;
  integrations: string[];
}

export interface ProjectStatus {
  id: string;
  name: string;
  state: ProjectState;
  path?: 'docs' | 'interview' | null;
  platform?: 'claude_code' | 'cursor' | 'windsurf' | 'github_copilot' | null;
  blockers: string[];
  /** Persisted context — lets the wizard restore answers after Back / reload. */
  brief?: ProjectBrief | null;
  plan?: ProjectPlan | null;
  interview: InterviewQuestion[];
  error?: string | null;
  progress?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  user_id?: string | null;
  /**
   * Blueprint flags. Optional so an older backend that omits them reads as "no diagrams",
   * which is exactly the pre-existing behaviour.
   */
  has_diagrams?: boolean;
  diagrams_frozen?: boolean;
  diagram_version?: number;
}

/** SIPOC / process flow / swimlane — three views of one extracted process model. */
export type DiagramKind = 'sipoc' | 'flow' | 'swimlane';

/**
 * What a follow-up is allowed to change.
 *
 * `all` revises the shared process model, so all three views are redrawn and stay in agreement —
 * the only way to change what the process *is*. A single kind re-lays out that one picture and
 * leaves the model alone, which is why "only this diagram" cannot produce three views that
 * disagree: the process behind them never moved.
 */
export type DiagramScope = 'all' | DiagramKind;

/**
 * SDD.md §3.2's three architectural views — a different artefact from `DiagramKind`.
 *
 * The blueprint is the business process being automated and carries an approved version;
 * these are the software architecture as the current design describes it, so they have no
 * version and are redrawn whenever the design changes. Mirrors `ARCH_KINDS` in
 * `backend/app/services/diagrams/architecture.py`.
 */
export type ArchitectureKind = 'logical' | 'development' | 'deployment';

/**
 * The two formats SDD.md downloads as. Mirrors `DOC_FORMATS` in
 * `backend/app/services/export/documents.py`, which parses the markdown once and emits both —
 * so the PDF and the DOCX are the same document, laid out the same way this app previews it.
 */
export type DocumentFormat = 'pdf' | 'docx';

/*
 * Narrowing guards for the two kinds above.
 *
 * `ac-diagram-viewer` shows both families — the blueprint and SDD §3.2's architecture views —
 * so the id it emits when the reader switches view is a plain string rather than either union.
 * These are how a caller gets back to its own kind: one guard each, listing the values once,
 * instead of a cast at every call site that would happily pass `'sipoc'` to an architecture
 * lookup.
 */
export function isDiagramKind(value: string): value is DiagramKind {
  return value === 'sipoc' || value === 'flow' || value === 'swimlane';
}

export function isArchitectureKind(value: string): value is ArchitectureKind {
  return value === 'logical' || value === 'development' || value === 'deployment';
}

export interface ProcessActor {
  name: string;
  kind: 'human' | 'system' | 'external';
  responsibilities: string;
}

export interface ProcessStep {
  id: string;
  name: string;
  kind: 'start' | 'task' | 'decision' | 'subprocess' | 'end';
  actor: string;
  description: string;
  systems: string[];
  inputs: string[];
  outputs: string[];
}

export interface ProcessEdge {
  source: string;
  target: string;
  label: string;
}

export interface ProcessModel {
  title: string;
  scope: string;
  actors: ProcessActor[];
  systems: string[];
  steps: ProcessStep[];
  edges: ProcessEdge[];
  data_objects: string[];
  kpis: string[];
  assumptions: string[];
}

export interface SipocItem {
  name: string;
  note: string;
}

export interface SipocDiagram {
  title: string;
  suppliers: SipocItem[];
  inputs: SipocItem[];
  process: SipocItem[];
  outputs: SipocItem[];
  customers: SipocItem[];
  metrics: string[];
}

export interface DiagramRevision {
  version: number;
  instruction: string;
  summary: string;
  /**
   * What this revision was allowed to touch. Absent on revisions recorded before the choice
   * existed — those all redrew everything, so a missing value reads as `all`.
   */
  scope?: DiagramScope | string;
  created_at?: string | null;
  /**
   * True when this version's diagrams can still be drawn.
   *
   * Only the last few versions keep the views needed to redraw them (see `HISTORY_LIMIT` in
   * the backend), so an old entry stays in the list as a record of what changed but has no
   * images behind it.
   */
  viewable?: boolean;
}

export interface DiagramImage {
  kind: DiagramKind;
  /** True pixel width of the PNG. Divide by `scale` for the size it is meant to be read at. */
  width: number;
  height: number;
  bytes: number;
  /** Device pixels per layout pixel — 2 means the PNG is drawn at twice its reading size. */
  scale?: number;
}

export interface DiagramSetView {
  project_id: string;
  version: number;
  frozen: boolean;
  frozen_at?: string | null;
  /** False when the deterministic fallback drew these (demo mode, or a failed layout call). */
  llm: boolean;
  model: ProcessModel;
  sipoc: SipocDiagram;
  /** Flow and swimlane bodies are only needed for counts in the UI, so they stay loose. */
  flow: { title: string; nodes: { id: string }[]; edges: ProcessEdge[] };
  swimlane: { title: string; lanes: string[]; steps: { id: string }[]; edges: ProcessEdge[] };
  warnings: string[];
  revisions: DiagramRevision[];
  images: DiagramImage[];
  updated_at?: string | null;
}

export interface PlatformInfo {
  id: string;
  label: string;
  blurb: string;
}

export interface User {
  id: string;
  email: string;
  name: string;
  role?: 'user' | 'admin' | string;
  status?: 'pending' | 'approved' | 'rejected' | string;
}

export interface AuthResponse {
  access_token: string;
  token_type: string;
  user: User;
}

export interface SignupPendingResponse {
  message: string;
  status: 'pending' | string;
  email: string;
}

export interface AdminSessionInfo {
  id: string;
  name: string;
  state: string;
  platform?: string | null;
  updated_at?: string | null;
  agent_count: number;
  skill_count: number;
  rule_count: number;
  agent_names: string[];
  skill_names: string[];
  rule_names: string[];
  /** Optional so an older backend that omits it doesn't break the panel. */
  document_names?: string[];
  /**
   * Which context pipeline the session followed — `docs` (uploaded documents) or
   * `interview` (guided questions). Null when the fork was never taken.
   */
  path?: 'docs' | 'interview' | string | null;
  /** True when the pipeline was deduced from the session's contents, not read from the row. */
  path_inferred?: boolean;
  interview_answer_count?: number;
  /** Blueprint metadata. The PNGs come from the admin diagram endpoints on demand. */
  has_diagrams?: boolean;
  diagrams_frozen?: boolean;
  diagram_version?: number;
  diagram_title?: string | null;
  diagram_step_count?: number;
  diagram_actor_count?: number;
  /** Change-history entries, first draft included. */
  diagram_revision_count?: number;
  /** Scope of the most recent follow-up; null when the first draft was never revised. */
  diagram_last_scope?: DiagramScope | string | null;
  /**
   * The session has a generated plan, so SDD.md and its three architectural views exist.
   *
   * Same purpose as `has_diagrams`: it decides whether the panel asks for the architecture
   * PNGs at all, so nothing is rendered speculatively. Optional so an older backend that
   * omits it simply shows no architecture section.
   */
  has_plan?: boolean;
}

export interface AdminUserView {
  id: string;
  email: string;
  name: string;
  role: string;
  /** `deleted` rows come from the archive, not the users table — they are restorable. */
  status: 'pending' | 'approved' | 'rejected' | 'deleted' | string;
  created_at?: string | null;
  session_count: number;
  sessions: AdminSessionInfo[];
  deleted_at?: string | null;
  deleted_by?: string | null;
  /** Status the account held when it was deleted — what restore brings back. */
  previous_status?: string | null;
  /** False for archives written before restore existed; only purge applies to those. */
  restorable?: boolean;
}

/** Response of DELETE /admin/users/{id} — login is revoked, workspaces held for restore. */
export interface DeleteUserResult {
  id: string;
  email: string;
  name: string;
  deleted_sessions: number;
  message: string;
  restorable?: boolean;
}

/** Response of POST /admin/users/{id}/restore — the account and its workspaces are back. */
export interface RestoreUserResult {
  user: AdminUserView;
  restored_sessions: number;
  message: string;
}

/** Response of DELETE /admin/users/{id}/purge — erased for good. */
export interface PurgeUserResult {
  id: string;
  email: string;
  purged_sessions: number;
  message: string;
}

export interface SessionSummary {
  id: string;
  name: string;
  state: ProjectState;
  platform?: 'claude_code' | 'cursor' | 'windsurf' | 'github_copilot' | null;
  summary?: string | null;
  agent_count: number;
  skill_count: number;
  rule_count: number;
  agent_names?: string[];
  skill_names?: string[];
  rule_names?: string[];
  /** Uploaded source documents for this session (docs path only). */
  document_names?: string[];
  created_at?: string | null;
  updated_at?: string | null;
}
